#if VELO_CE == 1
#ifdef _COMMCTRL_H
#ifndef CCS_NOHILITE
#define CCS_NOHILITE 16
#endif
#ifndef CLR_HILIGHT
#define CLR_HILIGHT 0xFF000000U
#endif
#ifndef CMDBAR_HELP
#define CMDBAR_HELP 11
#endif
#ifndef CMDBAR_OK
#define CMDBAR_OK 0xF000
#endif
#ifndef HDI_ALL
#define HDI_ALL 191
#endif
#ifndef HDS_DIVIDERTRACK
#define HDS_DIVIDERTRACK 4
#endif
#ifndef HDS_DRAGDROP
#define HDS_DRAGDROP 64
#endif
#ifndef HIST_ADDTOFAVORITES
#define HIST_ADDTOFAVORITES 3
#endif
#ifndef HIST_BACK
#define HIST_BACK 0
#endif
#ifndef HIST_FAVORITES
#define HIST_FAVORITES 2
#endif
#ifndef HIST_FORWARD
#define HIST_FORWARD 1
#endif
#ifndef HIST_LAST
#define HIST_LAST 4
#endif
#ifndef HIST_VIEWTREE
#define HIST_VIEWTREE 4
#endif
#ifndef IDB_STD_LARGE_MONO
#define IDB_STD_LARGE_MONO 3
#endif
#ifndef IDB_STD_SMALL_MONO
#define IDB_STD_SMALL_MONO 2
#endif
#ifndef IDB_VIEW_LARGE_MONO
#define IDB_VIEW_LARGE_MONO 7
#endif
#ifndef IDB_VIEW_SMALL_MONO
#define IDB_VIEW_SMALL_MONO 6
#endif
#ifndef ILC_COLORMASK
#define ILC_COLORMASK 254
#endif
#ifndef ILC_LARGESMALL
#define ILC_LARGESMALL 0x200
#endif
#ifndef ILC_SHARED
#define ILC_SHARED 0x100
#endif
#ifndef ILC_UNIQUE
#define ILC_UNIQUE 0x400
#endif
#ifndef ILC_VALID
#define ILC_VALID 0x81FF
#endif
#ifndef ILC_VIRTUAL
#define ILC_VIRTUAL 0x8000
#endif
#ifndef ILD_BLEND75
#define ILD_BLEND75 8
#endif
#ifndef ILD_BLENDMASK
#define ILD_BLENDMASK 14
#endif
#ifndef I_INDENTCALLBACK
#define I_INDENTCALLBACK (-1)
#endif
#ifndef LVA_ALIGNBOTTOM
#define LVA_ALIGNBOTTOM 4
#endif
#ifndef LVA_ALIGNMASK
#define LVA_ALIGNMASK 7
#endif
#ifndef LVA_ALIGNRIGHT
#define LVA_ALIGNRIGHT 3
#endif
#ifndef LVA_SORTASCENDING
#define LVA_SORTASCENDING 0x100
#endif
#ifndef LVA_SORTDESCENDING
#define LVA_SORTDESCENDING 0x200
#endif
#ifndef LVCF_ALL
#define LVCF_ALL 63
#endif
#ifndef LVFI_NOCASE
#define LVFI_NOCASE 16
#endif
#ifndef LVFI_SUBSTRING
#define LVFI_SUBSTRING 4
#endif
#ifndef LVIF_ALL
#define LVIF_ALL 31
#endif
#ifndef LVIF_RESERVED
#define LVIF_RESERVED 0xF000
#endif
#ifndef LVIR_MAX
#define LVIR_MAX 4
#endif
#ifndef LVIS_ALL
#define LVIS_ALL 0xFFFF
#endif
#ifndef LVIS_DISABLED
#define LVIS_DISABLED 16
#endif
#ifndef LVIS_LINK
#define LVIS_LINK 64
#endif
#ifndef LVNI_PREVIOUS
#define LVNI_PREVIOUS 32
#endif
#ifndef LVN_ENDDRAG
#define LVN_ENDDRAG 0xFFFFFF92U
#endif
#ifndef LVN_ENDRDRAG
#define LVN_ENDRDRAG 0xFFFFFF90U
#endif
#ifndef LVN_MARQUEEBEGIN
#define LVN_MARQUEEBEGIN 0xFFFFFF64U
#endif
#ifndef LVSIL_HEADER
#define LVSIL_HEADER 3
#endif
#ifndef LVS_ALIGNBOTTOM
#define LVS_ALIGNBOTTOM 0x400
#endif
#ifndef LVS_ALIGNRIGHT
#define LVS_ALIGNRIGHT 0xC00
#endif
#ifndef NM_BTNCLK
#define NM_BTNCLK 0xFFFFFFF5U
#endif
#ifndef NM_ENDWAIT
#define NM_ENDWAIT 0xFFFFFFF6U
#endif
#ifndef NM_STARTWAIT
#define NM_STARTWAIT 0xFFFFFFF7U
#endif
#ifndef PBS_SHOWPERCENT
#define PBS_SHOWPERCENT 1
#endif
#ifndef PBS_SHOWPOS
#define PBS_SHOWPOS 2
#endif
#ifndef SB_SETBORDERS
#define SB_SETBORDERS 0x405
#endif
#ifndef TBBF_MONO
#define TBBF_MONO 2
#endif
#ifndef TBN_CLOSEUP
#define TBN_CLOSEUP 0xFFFFFD39U
#endif
#ifndef TBN_GETBUTTONINFOW
#define TBN_GETBUTTONINFOW 0xFFFFFD30U
#endif
#ifndef TB_ADDBITMAP32
#define TB_ADDBITMAP32 0x426
#endif
#ifndef TB_SETBUTTONTYPE
#define TB_SETBUTTONTYPE 0x422
#endif
#ifndef TB_SETTOOLTIPSA
#define TB_SETTOOLTIPSA 0x450
#endif
#ifndef TB_SETTOOLTIPSW
#define TB_SETTOOLTIPSW 0x451
#endif
#ifndef TCIF_ALL
#define TCIF_ALL 31
#endif
#ifndef TCIF_STATE
#define TCIF_STATE 16
#endif
#ifndef TCM_GETBKCOLOR
#define TCM_GETBKCOLOR 0x1300
#endif
#ifndef TCM_SETBKCOLOR
#define TCM_SETBKCOLOR 0x1301
#endif
#ifndef TCN_BEGINSCROLL
#define TCN_BEGINSCROLL 0xFFFFFDD7U
#endif
#ifndef TCN_ENDSCROLL
#define TCN_ENDSCROLL 0xFFFFFDD6U
#endif
#ifndef TCS_FLIP
#define TCS_FLIP 64
#endif
#ifndef TTF_STRIPACCELS
#define TTF_STRIPACCELS 8
#endif
#ifndef TTF_UNICODE
#define TTF_UNICODE 64
#endif
#ifndef TVE_ACTIONMASK
#define TVE_ACTIONMASK 3
#endif
#ifndef TVIF_ALL
#define TVIF_ALL 127
#endif
#ifndef TVIF_RESERVED
#define TVIF_RESERVED 0xF000
#endif
#ifndef TVIS_ALL
#define TVIS_ALL 0xFF7E
#endif
#ifndef TVIS_DISABLED
#define TVIS_DISABLED 0
#endif
#ifndef TVIS_EXPANDPARTIAL
#define TVIS_EXPANDPARTIAL 128
#endif
#ifndef TVS_PRIVATEIMAGELISTS
#define TVS_PRIVATEIMAGELISTS 64
#endif
#ifndef TVS_SHAREDIMAGELISTS
#define TVS_SHAREDIMAGELISTS 0
#endif
#endif
#ifdef _MMSYSTEM_H
#ifndef MM_MICROSOFT
#define MM_MICROSOFT 1
#endif
#ifndef SND_RESERVED
#define SND_RESERVED 0xFF000000U
#endif
#ifndef SND_TYPE_MASK
#define SND_TYPE_MASK 0x170007
#endif
#ifndef SND_VALIDFLAGS
#define SND_VALIDFLAGS 0x17201F
#endif
#endif
#ifdef _PRSHT_H
#ifndef PSH_ALL
#define PSH_ALL 0xFFF
#endif
#ifndef PSN_HASHELP
#define PSN_HASHELP 0xFFFFFF34U
#endif
#endif
#ifdef _RAS_H
#ifndef RASNP_Netbeui
#define RASNP_Netbeui 1
#endif
#ifndef RAS_MaxParamKey
#define RAS_MaxParamKey 32
#endif
#ifndef RAS_MaxParamValue
#define RAS_MaxParamValue 128
#endif
#ifndef RNA_ADDREF
#define RNA_ADDREF 1
#endif
#ifndef RNA_DELREF
#define RNA_DELREF 2
#endif
#ifndef RNA_RASCMD
#define RNA_RASCMD 0x401
#endif
#endif
#ifdef _SHELLAPI_H
#ifndef SHARD_PATH
#define SHARD_PATH 2
#endif
#ifndef SHARD_PIDL
#define SHARD_PIDL 1
#endif
#ifndef SHORTCUT_OVERWRITE
#define SHORTCUT_OVERWRITE 1
#endif
#endif
#ifdef _WINBASE_H
#ifndef CLRIR
#define CLRIR 11
#endif
#ifndef COMMPROP_INITIALIZED
#define COMMPROP_INITIALIZED 0xE73CF52EU
#endif
#ifndef EV_POWER
#define EV_POWER 0x2000
#endif
#ifndef IE_BADID
#define IE_BADID (-1)
#endif
#ifndef IE_BAUDRATE
#define IE_BAUDRATE (-12)
#endif
#ifndef IE_BYTESIZE
#define IE_BYTESIZE (-11)
#endif
#ifndef IE_DEFAULT
#define IE_DEFAULT (-5)
#endif
#ifndef IE_HARDWARE
#define IE_HARDWARE (-10)
#endif
#ifndef IE_MEMORY
#define IE_MEMORY (-4)
#endif
#ifndef IE_NOPEN
#define IE_NOPEN (-3)
#endif
#ifndef IE_OPEN
#define IE_OPEN (-2)
#endif
#ifndef LMEM_VALID_FLAGS
#define LMEM_VALID_FLAGS 0xF72
#endif
#ifndef LPTx
#define LPTx 128
#endif
#ifndef MEM_AUTO_COMMIT
#define MEM_AUTO_COMMIT 0x200000
#endif
#ifndef OPEN_FOR_LOADER
#define OPEN_FOR_LOADER 6
#endif
#ifndef PROCESSOR_HITACHI_SH3
#define PROCESSOR_HITACHI_SH3 0x2713
#endif
#ifndef PROCESSOR_INTEL_860
#define PROCESSOR_INTEL_860 0x35C
#endif
#ifndef PROCESSOR_MIPS_R2000
#define PROCESSOR_MIPS_R2000 0x7D0
#endif
#ifndef PROCESSOR_MIPS_R3000
#define PROCESSOR_MIPS_R3000 0xBB8
#endif
#ifndef RESETDEV
#define RESETDEV 7
#endif
#ifndef SETIR
#define SETIR 10
#endif
#ifndef VER_PLATFORM_WIN32_HH
#define VER_PLATFORM_WIN32_HH 3
#endif
#endif
#ifdef _WINGDI_H
#ifndef CP_NONE
#define CP_NONE 0
#endif
#ifndef CP_RECTANGLE
#define CP_RECTANGLE 1
#endif
#ifndef CP_REGION
#define CP_REGION 2
#endif
#ifndef RGN_ERROR
#define RGN_ERROR 0
#endif
#ifndef RGN_MAX
#define RGN_MAX 5
#endif
#ifndef RGN_MIN
#define RGN_MIN 1
#endif
#endif
#ifdef _WINNLS_H
#ifndef NLS_DEFAULT_ACP
#define NLS_DEFAULT_ACP 0x4E4
#endif
#ifndef NLS_DEFAULT_LANGID
#define NLS_DEFAULT_LANGID 0x409
#endif
#ifndef NLS_DEFAULT_LOCALE
#define NLS_DEFAULT_LOCALE 0x409
#endif
#ifndef NLS_DEFAULT_OEMCP
#define NLS_DEFAULT_OEMCP 0x1B5
#endif
#endif
#ifdef _WINNT_H
#ifndef EXCEPTION_COLLIDED_UNWIND
#define EXCEPTION_COLLIDED_UNWIND 64
#endif
#ifndef EXCEPTION_EXIT_UNWIND
#define EXCEPTION_EXIT_UNWIND 4
#endif
#ifndef EXCEPTION_NESTED_CALL
#define EXCEPTION_NESTED_CALL 16
#endif
#ifndef EXCEPTION_STACK_INVALID
#define EXCEPTION_STACK_INVALID 8
#endif
#ifndef EXCEPTION_TARGET_UNWIND
#define EXCEPTION_TARGET_UNWIND 32
#endif
#ifndef EXCEPTION_UNWIND
#define EXCEPTION_UNWIND 102
#endif
#ifndef EXCEPTION_UNWINDING
#define EXCEPTION_UNWINDING 2
#endif
#ifndef FILE_ATTRIBUTE_ATOMIC_WRITE
#define FILE_ATTRIBUTE_ATOMIC_WRITE 0x200
#endif
#ifndef FILE_ATTRIBUTE_ROMSTATICREF
#define FILE_ATTRIBUTE_ROMSTATICREF 0x1000
#endif
#ifndef FILE_ATTRIBUTE_XACTION_WRITE
#define FILE_ATTRIBUTE_XACTION_WRITE 0x400
#endif
#ifndef PROCESSOR_PPC_601
#define PROCESSOR_PPC_601 0x259
#endif
#ifndef PROCESSOR_PPC_603
#define PROCESSOR_PPC_603 0x25B
#endif
#ifndef PROCESSOR_PPC_604
#define PROCESSOR_PPC_604 0x25C
#endif
#ifndef PROCESSOR_PPC_620
#define PROCESSOR_PPC_620 0x26C
#endif
#ifndef PROCESSOR_PPC_821
#define PROCESSOR_PPC_821 0x335
#endif
#ifndef REG_LEGAL_CHANGE_FILTER
#define REG_LEGAL_CHANGE_FILTER 15
#endif
#ifndef STATUS_INSTRUCTION_MISALIGNMENT
#define STATUS_INSTRUCTION_MISALIGNMENT 0xC00000AAU
#endif
#ifndef STATUS_INVALID_PARAMETER
#define STATUS_INVALID_PARAMETER 0xC000000DU
#endif
#ifndef STATUS_INVALID_SYSTEM_SERVICE
#define STATUS_INVALID_SYSTEM_SERVICE 0xC000001CU
#endif
#ifndef STATUS_SUCCESS
#define STATUS_SUCCESS 0
#endif
#ifndef STATUS_UNSUCCESSFUL
#define STATUS_UNSUCCESSFUL 0xC0000001U
#endif
#ifndef STATUS_USER_BREAK
#define STATUS_USER_BREAK 0x80000113U
#endif
#endif
#ifdef _WINREG_H
#ifndef WIN31_CLASS
#define WIN31_CLASS 0
#endif
#endif
#ifdef _WINSOCK_H
#ifndef AF_PAGER
#define AF_PAGER 21
#endif
#ifndef EADDRINUSE
#define EADDRINUSE 0x2740
#endif
#ifndef EADDRNOTAVAIL
#define EADDRNOTAVAIL 0x2741
#endif
#ifndef EAFNOSUPPORT
#define EAFNOSUPPORT 0x273F
#endif
#ifndef EALREADY
#define EALREADY 0x2735
#endif
#ifndef ECONNABORTED
#define ECONNABORTED 0x2745
#endif
#ifndef ECONNREFUSED
#define ECONNREFUSED 0x274D
#endif
#ifndef ECONNRESET
#define ECONNRESET 0x2746
#endif
#ifndef EDESTADDRREQ
#define EDESTADDRREQ 0x2737
#endif
#ifndef EDQUOT
#define EDQUOT 0x2755
#endif
#ifndef EHOSTDOWN
#define EHOSTDOWN 0x2750
#endif
#ifndef EHOSTUNREACH
#define EHOSTUNREACH 0x2751
#endif
#ifndef EINPROGRESS
#define EINPROGRESS 0x2734
#endif
#ifndef EISCONN
#define EISCONN 0x2748
#endif
#ifndef ELOOP
#define ELOOP 0x274E
#endif
#ifndef EMSGSIZE
#define EMSGSIZE 0x2738
#endif
#ifndef ENAMETOOLONG
#define ENAMETOOLONG 0x274F
#endif
#ifndef ENETDOWN
#define ENETDOWN 0x2742
#endif
#ifndef ENETRESET
#define ENETRESET 0x2744
#endif
#ifndef ENETUNREACH
#define ENETUNREACH 0x2743
#endif
#ifndef ENOBUFS
#define ENOBUFS 0x2747
#endif
#ifndef ENOPROTOOPT
#define ENOPROTOOPT 0x273A
#endif
#ifndef ENOTCONN
#define ENOTCONN 0x2749
#endif
#ifndef ENOTEMPTY
#define ENOTEMPTY 0x2752
#endif
#ifndef ENOTSOCK
#define ENOTSOCK 0x2736
#endif
#ifndef EOPNOTSUPP
#define EOPNOTSUPP 0x273D
#endif
#ifndef EPFNOSUPPORT
#define EPFNOSUPPORT 0x273E
#endif
#ifndef EPROCLIM
#define EPROCLIM 0x2753
#endif
#ifndef EPROTONOSUPPORT
#define EPROTONOSUPPORT 0x273B
#endif
#ifndef EPROTOTYPE
#define EPROTOTYPE 0x2739
#endif
#ifndef EREMOTE
#define EREMOTE 0x2757
#endif
#ifndef ESHUTDOWN
#define ESHUTDOWN 0x274A
#endif
#ifndef ESOCKTNOSUPPORT
#define ESOCKTNOSUPPORT 0x273C
#endif
#ifndef ESTALE
#define ESTALE 0x2756
#endif
#ifndef ETIMEDOUT
#define ETIMEDOUT 0x274C
#endif
#ifndef ETOOMANYREFS
#define ETOOMANYREFS 0x274B
#endif
#ifndef EUSERS
#define EUSERS 0x2754
#endif
#ifndef EWOULDBLOCK
#define EWOULDBLOCK 0x2733
#endif
#endif
#ifdef _WINUSER_H
#ifndef CBS_EX_CONSTSTRINGDATA
#define CBS_EX_CONSTSTRINGDATA 2
#endif
#ifndef CB_MSGMAX
#define CB_MSGMAX 0x163
#endif
#ifndef CB_MULTIPLEADDSTRING
#define CB_MULTIPLEADDSTRING 0x163
#endif
#ifndef COLOR_LASTITEM
#define COLOR_LASTITEM 0x40000019
#endif
#ifndef CTLCOLOR_SCOLLBAR
#define CTLCOLOR_SCOLLBAR 5
#endif
#ifndef ES_COMBOBOX
#define ES_COMBOBOX 0x200
#endif
#ifndef EW_EXITANDEXECAPP
#define EW_EXITANDEXECAPP 68
#endif
#ifndef EW_REBOOTSYSTEM
#define EW_REBOOTSYSTEM 67
#endif
#ifndef EW_RESTARTWINDOWS
#define EW_RESTARTWINDOWS 66
#endif
#ifndef FLASTKEY
#define FLASTKEY 128
#endif
#ifndef GW_MAX
#define GW_MAX 5
#endif
#ifndef HSHELL_CAPSLOCK
#define HSHELL_CAPSLOCK 8
#endif
#ifndef INI_INTL
#define INI_INTL 1
#endif
#ifndef LBS_EX_CONSTSTRINGDATA
#define LBS_EX_CONSTSTRINGDATA 2
#endif
#ifndef LB_MSGMAX
#define LB_MSGMAX 0x1B1
#endif
#ifndef LB_MULTIPLEADDSTRING
#define LB_MULTIPLEADDSTRING 0x1B1
#endif
#ifndef STM_SETCOLORS
#define STM_SETCOLORS 0x400
#endif
#ifndef SWP_BEGINDEFERWINDOWPOS
#define SWP_BEGINDEFERWINDOWPOS 0x8000
#endif
#ifndef SWP_ENDDEFERWINDOWPOS
#define SWP_ENDDEFERWINDOWPOS 0x4000
#endif
#ifndef VK_APOSTROPHE
#define VK_APOSTROPHE 222
#endif
#ifndef VK_BACKQUOTE
#define VK_BACKQUOTE 192
#endif
#ifndef VK_BACKSLASH
#define VK_BACKSLASH 220
#endif
#ifndef VK_COMMA
#define VK_COMMA 188
#endif
#ifndef VK_EQUAL
#define VK_EQUAL 187
#endif
#ifndef VK_HYPHEN
#define VK_HYPHEN 189
#endif
#ifndef VK_LBRACKET
#define VK_LBRACKET 219
#endif
#ifndef VK_OEM_102
#define VK_OEM_102 226
#endif
#ifndef VK_PERIOD
#define VK_PERIOD 190
#endif
#ifndef VK_RBRACKET
#define VK_RBRACKET 221
#endif
#ifndef VK_SEMICOLON
#define VK_SEMICOLON 186
#endif
#ifndef VK_SLASH
#define VK_SLASH 191
#endif
#ifndef WM_NETCONNECT
#define WM_NETCONNECT 0x3FE
#endif
#ifndef WS_EX_ABOVESTARTUP
#define WS_EX_ABOVESTARTUP 0x20000000
#endif
#ifndef WS_EX_NODRAG
#define WS_EX_NODRAG 0x40000000
#endif
#endif
#endif

#if VELO_CE == 2
#ifdef _COMMCTRL_H
#ifndef CLR_HILIGHT
#define CLR_HILIGHT 0xFF000000U
#endif
#ifndef DTM_FIRST
#define DTM_FIRST 0x1000
#endif
#ifndef I_INDENTCALLBACK
#define I_INDENTCALLBACK (-1)
#endif
#ifndef LVIS_ALL
#define LVIS_ALL 0xFFFF
#endif
#ifndef LVSIL_HEADER
#define LVSIL_HEADER 3
#endif
#ifndef MCM_FIRST
#define MCM_FIRST 0x1000
#endif
#ifndef RBS_SMARTLABELS
#define RBS_SMARTLABELS 0x1000
#endif
#ifndef TBSTATE_HIGHLIGHTED
#define TBSTATE_HIGHLIGHTED 128
#endif
#ifndef TB_HIGHLIGHTBUTTON
#define TB_HIGHLIGHTBUTTON 0x406
#endif
#ifndef TVIS_EXPANDPARTIAL
#define TVIS_EXPANDPARTIAL 128
#endif
#endif
#ifdef _COMMDLG_H
#ifndef CDERR_DIALOGFAILURE
#define CDERR_DIALOGFAILURE 0xFFFF
#endif
#ifndef CDERR_FINDRESFAILURE
#define CDERR_FINDRESFAILURE 4
#endif
#ifndef CDERR_INITIALIZATION
#define CDERR_INITIALIZATION 2
#endif
#ifndef CDERR_LOADRESFAILURE
#define CDERR_LOADRESFAILURE 5
#endif
#ifndef CDERR_LOCKRESFAILURE
#define CDERR_LOCKRESFAILURE 6
#endif
#ifndef CDERR_MEMALLOCFAILURE
#define CDERR_MEMALLOCFAILURE 7
#endif
#ifndef CDERR_NOHINSTANCE
#define CDERR_NOHINSTANCE 10
#endif
#ifndef CDERR_NOHOOK
#define CDERR_NOHOOK 8
#endif
#ifndef CDERR_NOTEMPLATE
#define CDERR_NOTEMPLATE 3
#endif
#ifndef CDERR_REGISTRYFAILURE
#define CDERR_REGISTRYFAILURE 9
#endif
#ifndef CDERR_STRUCTSIZE
#define CDERR_STRUCTSIZE 1
#endif
#ifndef OFN_PROJECT
#define OFN_PROJECT 0x400000
#endif
#ifndef OFN_PROPERTY
#define OFN_PROPERTY 0x800000
#endif
#ifndef PDERR_CREATEDCFAILURE
#define PDERR_CREATEDCFAILURE 0x1004
#endif
#ifndef PDERR_NODEFAULTPRN
#define PDERR_NODEFAULTPRN 0x1000
#endif
#ifndef PDERR_NOPORTS
#define PDERR_NOPORTS 0x1002
#endif
#ifndef PDERR_NOPRINTERS
#define PDERR_NOPRINTERS 0x1003
#endif
#ifndef PDERR_PRINTERNOTFOUND
#define PDERR_PRINTERNOTFOUND 0x1001
#endif
#endif
#ifdef _MMSYSTEM_H
#ifndef SND_RESERVED
#define SND_RESERVED 0xFF000000U
#endif
#ifndef SND_TYPE_MASK
#define SND_TYPE_MASK 0x170007
#endif
#ifndef SND_VALIDFLAGS
#define SND_VALIDFLAGS 0x17201F
#endif
#endif
#ifdef _MSACM_H
#ifndef ACMDM_BASE
#define ACMDM_BASE 0x6000
#endif
#ifndef ACMDM_DRIVER_ABOUT
#define ACMDM_DRIVER_ABOUT 0x600B
#endif
#ifndef ACMDM_RESERVED_HIGH
#define ACMDM_RESERVED_HIGH 0x6FFF
#endif
#ifndef ACMDM_RESERVED_LOW
#define ACMDM_RESERVED_LOW 0x6000
#endif
#ifndef ACMDM_USER
#define ACMDM_USER 0x4000
#endif
#ifndef ACMDRIVERDETAILS_FCCCOMP_UNDEFINED
#define ACMDRIVERDETAILS_FCCCOMP_UNDEFINED 0
#endif
#ifndef ACMDRIVERDETAILS_FCCTYPE_AUDIOCODEC
#define ACMDRIVERDETAILS_FCCTYPE_AUDIOCODEC 0x63647561
#endif
#ifndef ACMDRIVERDETAILS_SUPPORTF_ASYNC
#define ACMDRIVERDETAILS_SUPPORTF_ASYNC 16
#endif
#ifndef ACMDRIVERDETAILS_SUPPORTF_CODEC
#define ACMDRIVERDETAILS_SUPPORTF_CODEC 1
#endif
#ifndef ACMDRIVERDETAILS_SUPPORTF_CONVERTER
#define ACMDRIVERDETAILS_SUPPORTF_CONVERTER 2
#endif
#ifndef ACMDRIVERDETAILS_SUPPORTF_DISABLED
#define ACMDRIVERDETAILS_SUPPORTF_DISABLED 0x80000000U
#endif
#ifndef ACMDRIVERDETAILS_SUPPORTF_FILTER
#define ACMDRIVERDETAILS_SUPPORTF_FILTER 4
#endif
#ifndef ACMDRIVERDETAILS_SUPPORTF_HARDWARE
#define ACMDRIVERDETAILS_SUPPORTF_HARDWARE 8
#endif
#ifndef ACMDRIVERDETAILS_SUPPORTF_LOCAL
#define ACMDRIVERDETAILS_SUPPORTF_LOCAL 0x40000000
#endif
#ifndef ACMERR_BASE
#define ACMERR_BASE 0x200
#endif
#ifndef ACMERR_BUSY
#define ACMERR_BUSY 0x201
#endif
#ifndef ACMERR_CANCELED
#define ACMERR_CANCELED 0x203
#endif
#ifndef ACMERR_NOTPOSSIBLE
#define ACMERR_NOTPOSSIBLE 0x200
#endif
#ifndef ACMERR_UNPREPARED
#define ACMERR_UNPREPARED 0x202
#endif
#ifndef ACMFILTERCHOOSE_STYLEF_CONTEXTHELP
#define ACMFILTERCHOOSE_STYLEF_CONTEXTHELP 128
#endif
#ifndef ACMFILTERCHOOSE_STYLEF_ENABLEHOOK
#define ACMFILTERCHOOSE_STYLEF_ENABLEHOOK 8
#endif
#ifndef ACMFILTERCHOOSE_STYLEF_ENABLETEMPLATE
#define ACMFILTERCHOOSE_STYLEF_ENABLETEMPLATE 16
#endif
#ifndef ACMFILTERCHOOSE_STYLEF_ENABLETEMPLATEHANDLE
#define ACMFILTERCHOOSE_STYLEF_ENABLETEMPLATEHANDLE 32
#endif
#ifndef ACMFILTERCHOOSE_STYLEF_INITTOFILTERSTRUCT
#define ACMFILTERCHOOSE_STYLEF_INITTOFILTERSTRUCT 64
#endif
#ifndef ACMFILTERCHOOSE_STYLEF_SHOWHELP
#define ACMFILTERCHOOSE_STYLEF_SHOWHELP 4
#endif
#ifndef ACMFILTERDETAILS_FILTER_CHARS
#define ACMFILTERDETAILS_FILTER_CHARS 128
#endif
#ifndef ACMFILTERTAGDETAILS_FILTERTAG_CHARS
#define ACMFILTERTAGDETAILS_FILTERTAG_CHARS 48
#endif
#ifndef ACMFORMATCHOOSE_STYLEF_CONTEXTHELP
#define ACMFORMATCHOOSE_STYLEF_CONTEXTHELP 128
#endif
#ifndef ACMFORMATCHOOSE_STYLEF_ENABLEHOOK
#define ACMFORMATCHOOSE_STYLEF_ENABLEHOOK 8
#endif
#ifndef ACMFORMATCHOOSE_STYLEF_ENABLETEMPLATE
#define ACMFORMATCHOOSE_STYLEF_ENABLETEMPLATE 16
#endif
#ifndef ACMFORMATCHOOSE_STYLEF_ENABLETEMPLATEHANDLE
#define ACMFORMATCHOOSE_STYLEF_ENABLETEMPLATEHANDLE 32
#endif
#ifndef ACMFORMATCHOOSE_STYLEF_INITTOWFXSTRUCT
#define ACMFORMATCHOOSE_STYLEF_INITTOWFXSTRUCT 64
#endif
#ifndef ACMFORMATCHOOSE_STYLEF_SHOWHELP
#define ACMFORMATCHOOSE_STYLEF_SHOWHELP 4
#endif
#ifndef ACMSTREAMHEADER_STATUSF_DONE
#define ACMSTREAMHEADER_STATUSF_DONE 0x10000
#endif
#ifndef ACMSTREAMHEADER_STATUSF_INQUEUE
#define ACMSTREAMHEADER_STATUSF_INQUEUE 0x100000
#endif
#ifndef ACMSTREAMHEADER_STATUSF_PREPARED
#define ACMSTREAMHEADER_STATUSF_PREPARED 0x20000
#endif
#ifndef ACM_DRIVERADDF_FUNCTION
#define ACM_DRIVERADDF_FUNCTION 3
#endif
#ifndef ACM_DRIVERADDF_GLOBAL
#define ACM_DRIVERADDF_GLOBAL 8
#endif
#ifndef ACM_DRIVERADDF_LOCAL
#define ACM_DRIVERADDF_LOCAL 0
#endif
#ifndef ACM_DRIVERADDF_NOTIFYHWND
#define ACM_DRIVERADDF_NOTIFYHWND 4
#endif
#ifndef ACM_DRIVERADDF_TYPEMASK
#define ACM_DRIVERADDF_TYPEMASK 7
#endif
#ifndef ACM_DRIVERENUMF_DISABLED
#define ACM_DRIVERENUMF_DISABLED 0x80000000U
#endif
#ifndef ACM_DRIVERENUMF_NOLOCAL
#define ACM_DRIVERENUMF_NOLOCAL 0x40000000
#endif
#ifndef ACM_DRIVERPRIORITYF_ABLEMASK
#define ACM_DRIVERPRIORITYF_ABLEMASK 3
#endif
#ifndef ACM_DRIVERPRIORITYF_BEGIN
#define ACM_DRIVERPRIORITYF_BEGIN 0x10000
#endif
#ifndef ACM_DRIVERPRIORITYF_DEFERMASK
#define ACM_DRIVERPRIORITYF_DEFERMASK 0x30000
#endif
#ifndef ACM_DRIVERPRIORITYF_DISABLE
#define ACM_DRIVERPRIORITYF_DISABLE 2
#endif
#ifndef ACM_DRIVERPRIORITYF_ENABLE
#define ACM_DRIVERPRIORITYF_ENABLE 1
#endif
#ifndef ACM_DRIVERPRIORITYF_END
#define ACM_DRIVERPRIORITYF_END 0x20000
#endif
#ifndef ACM_FILTERDETAILSF_FILTER
#define ACM_FILTERDETAILSF_FILTER 1
#endif
#ifndef ACM_FILTERDETAILSF_INDEX
#define ACM_FILTERDETAILSF_INDEX 0
#endif
#ifndef ACM_FILTERDETAILSF_QUERYMASK
#define ACM_FILTERDETAILSF_QUERYMASK 15
#endif
#ifndef ACM_FILTERENUMF_DWFILTERTAG
#define ACM_FILTERENUMF_DWFILTERTAG 0x10000
#endif
#ifndef ACM_FILTERTAGDETAILSF_FILTERTAG
#define ACM_FILTERTAGDETAILSF_FILTERTAG 1
#endif
#ifndef ACM_FILTERTAGDETAILSF_INDEX
#define ACM_FILTERTAGDETAILSF_INDEX 0
#endif
#ifndef ACM_FILTERTAGDETAILSF_LARGESTSIZE
#define ACM_FILTERTAGDETAILSF_LARGESTSIZE 2
#endif
#ifndef ACM_FILTERTAGDETAILSF_QUERYMASK
#define ACM_FILTERTAGDETAILSF_QUERYMASK 15
#endif
#ifndef ACM_FORMATDETAILSF_FORMAT
#define ACM_FORMATDETAILSF_FORMAT 1
#endif
#ifndef ACM_FORMATDETAILSF_INDEX
#define ACM_FORMATDETAILSF_INDEX 0
#endif
#ifndef ACM_FORMATDETAILSF_QUERYMASK
#define ACM_FORMATDETAILSF_QUERYMASK 15
#endif
#ifndef ACM_FORMATENUMF_CONVERT
#define ACM_FORMATENUMF_CONVERT 0x100000
#endif
#ifndef ACM_FORMATENUMF_HARDWARE
#define ACM_FORMATENUMF_HARDWARE 0x400000
#endif
#ifndef ACM_FORMATENUMF_INPUT
#define ACM_FORMATENUMF_INPUT 0x800000
#endif
#ifndef ACM_FORMATENUMF_NCHANNELS
#define ACM_FORMATENUMF_NCHANNELS 0x20000
#endif
#ifndef ACM_FORMATENUMF_NSAMPLESPERSEC
#define ACM_FORMATENUMF_NSAMPLESPERSEC 0x40000
#endif
#ifndef ACM_FORMATENUMF_OUTPUT
#define ACM_FORMATENUMF_OUTPUT 0x1000000
#endif
#ifndef ACM_FORMATENUMF_SUGGEST
#define ACM_FORMATENUMF_SUGGEST 0x200000
#endif
#ifndef ACM_FORMATENUMF_WBITSPERSAMPLE
#define ACM_FORMATENUMF_WBITSPERSAMPLE 0x80000
#endif
#ifndef ACM_FORMATENUMF_WFORMATTAG
#define ACM_FORMATENUMF_WFORMATTAG 0x10000
#endif
#ifndef ACM_FORMATSUGGESTF_NCHANNELS
#define ACM_FORMATSUGGESTF_NCHANNELS 0x20000
#endif
#ifndef ACM_FORMATSUGGESTF_NSAMPLESPERSEC
#define ACM_FORMATSUGGESTF_NSAMPLESPERSEC 0x40000
#endif
#ifndef ACM_FORMATSUGGESTF_TYPEMASK
#define ACM_FORMATSUGGESTF_TYPEMASK 0xFF0000
#endif
#ifndef ACM_FORMATSUGGESTF_WBITSPERSAMPLE
#define ACM_FORMATSUGGESTF_WBITSPERSAMPLE 0x80000
#endif
#ifndef ACM_FORMATTAGDETAILSF_FORMATTAG
#define ACM_FORMATTAGDETAILSF_FORMATTAG 1
#endif
#ifndef ACM_FORMATTAGDETAILSF_INDEX
#define ACM_FORMATTAGDETAILSF_INDEX 0
#endif
#ifndef ACM_FORMATTAGDETAILSF_LARGESTSIZE
#define ACM_FORMATTAGDETAILSF_LARGESTSIZE 2
#endif
#ifndef ACM_FORMATTAGDETAILSF_QUERYMASK
#define ACM_FORMATTAGDETAILSF_QUERYMASK 15
#endif
#ifndef ACM_METRIC_COUNT_CODECS
#define ACM_METRIC_COUNT_CODECS 2
#endif
#ifndef ACM_METRIC_COUNT_CONVERTERS
#define ACM_METRIC_COUNT_CONVERTERS 3
#endif
#ifndef ACM_METRIC_COUNT_DISABLED
#define ACM_METRIC_COUNT_DISABLED 5
#endif
#ifndef ACM_METRIC_COUNT_DRIVERS
#define ACM_METRIC_COUNT_DRIVERS 1
#endif
#ifndef ACM_METRIC_COUNT_FILTERS
#define ACM_METRIC_COUNT_FILTERS 4
#endif
#ifndef ACM_METRIC_COUNT_HARDWARE
#define ACM_METRIC_COUNT_HARDWARE 6
#endif
#ifndef ACM_METRIC_COUNT_LOCAL_CODECS
#define ACM_METRIC_COUNT_LOCAL_CODECS 21
#endif
#ifndef ACM_METRIC_COUNT_LOCAL_CONVERTERS
#define ACM_METRIC_COUNT_LOCAL_CONVERTERS 22
#endif
#ifndef ACM_METRIC_COUNT_LOCAL_DISABLED
#define ACM_METRIC_COUNT_LOCAL_DISABLED 24
#endif
#ifndef ACM_METRIC_COUNT_LOCAL_DRIVERS
#define ACM_METRIC_COUNT_LOCAL_DRIVERS 20
#endif
#ifndef ACM_METRIC_COUNT_LOCAL_FILTERS
#define ACM_METRIC_COUNT_LOCAL_FILTERS 23
#endif
#ifndef ACM_METRIC_DRIVER_PRIORITY
#define ACM_METRIC_DRIVER_PRIORITY 101
#endif
#ifndef ACM_METRIC_DRIVER_SUPPORT
#define ACM_METRIC_DRIVER_SUPPORT 100
#endif
#ifndef ACM_METRIC_HARDWARE_WAVE_INPUT
#define ACM_METRIC_HARDWARE_WAVE_INPUT 30
#endif
#ifndef ACM_METRIC_HARDWARE_WAVE_OUTPUT
#define ACM_METRIC_HARDWARE_WAVE_OUTPUT 31
#endif
#ifndef ACM_METRIC_MAX_SIZE_FILTER
#define ACM_METRIC_MAX_SIZE_FILTER 51
#endif
#ifndef ACM_METRIC_MAX_SIZE_FORMAT
#define ACM_METRIC_MAX_SIZE_FORMAT 50
#endif
#ifndef ACM_STREAMCONVERTF_BLOCKALIGN
#define ACM_STREAMCONVERTF_BLOCKALIGN 4
#endif
#ifndef ACM_STREAMCONVERTF_END
#define ACM_STREAMCONVERTF_END 32
#endif
#ifndef ACM_STREAMCONVERTF_START
#define ACM_STREAMCONVERTF_START 16
#endif
#ifndef ACM_STREAMOPENF_ASYNC
#define ACM_STREAMOPENF_ASYNC 2
#endif
#ifndef ACM_STREAMOPENF_QUERY
#define ACM_STREAMOPENF_QUERY 1
#endif
#ifndef ACM_STREAMSIZEF_QUERYMASK
#define ACM_STREAMSIZEF_QUERYMASK 15
#endif
#ifndef ACM_STREAMSIZEF_SOURCE
#define ACM_STREAMSIZEF_SOURCE 0
#endif
#ifndef DRVM_MAPPER_STATUS
#define DRVM_MAPPER_STATUS 0x2000
#endif
#ifndef DRV_MAPPER_PREFERRED_INPUT_GET
#define DRV_MAPPER_PREFERRED_INPUT_GET 0x4000
#endif
#ifndef DRV_MAPPER_PREFERRED_OUTPUT_GET
#define DRV_MAPPER_PREFERRED_OUTPUT_GET 0x4002
#endif
#ifndef FILTERCHOOSE_CUSTOM_VERIFY
#define FILTERCHOOSE_CUSTOM_VERIFY 2
#endif
#ifndef FILTERCHOOSE_FILTERTAG_VERIFY
#define FILTERCHOOSE_FILTERTAG_VERIFY 0
#endif
#ifndef FILTERCHOOSE_FILTER_VERIFY
#define FILTERCHOOSE_FILTER_VERIFY 1
#endif
#ifndef FILTERCHOOSE_MESSAGE
#define FILTERCHOOSE_MESSAGE 0
#endif
#ifndef FORMATCHOOSE_CUSTOM_VERIFY
#define FORMATCHOOSE_CUSTOM_VERIFY 2
#endif
#ifndef FORMATCHOOSE_FORMATTAG_VERIFY
#define FORMATCHOOSE_FORMATTAG_VERIFY 0
#endif
#ifndef FORMATCHOOSE_FORMAT_VERIFY
#define FORMATCHOOSE_FORMAT_VERIFY 1
#endif
#ifndef FORMATCHOOSE_MESSAGE
#define FORMATCHOOSE_MESSAGE 0
#endif
#ifndef MM_ACM_CLOSE
#define MM_ACM_CLOSE 0x3D5
#endif
#ifndef MM_ACM_DONE
#define MM_ACM_DONE 0x3D6
#endif
#ifndef MM_ACM_FILTERCHOOSE
#define MM_ACM_FILTERCHOOSE 0x8000
#endif
#ifndef MM_ACM_FORMATCHOOSE
#define MM_ACM_FORMATCHOOSE 0x8000
#endif
#ifndef MM_ACM_OPEN
#define MM_ACM_OPEN 0x3D4
#endif
#endif
#ifdef _RAS_H
#ifndef RASEO_DialAsLocalCall
#define RASEO_DialAsLocalCall 0x20000
#endif
#ifndef RASEO_SecureLocalFiles
#define RASEO_SecureLocalFiles 0x10000
#endif
#ifndef RASNP_Netbeui
#define RASNP_Netbeui 1
#endif
#ifndef RAS_MaxParamKey
#define RAS_MaxParamKey 32
#endif
#ifndef RAS_MaxParamValue
#define RAS_MaxParamValue 128
#endif
#ifndef RNA_ADDREF
#define RNA_ADDREF 1
#endif
#ifndef RNA_DELREF
#define RNA_DELREF 2
#endif
#ifndef RNA_RASCMD
#define RNA_RASCMD 0x401
#endif
#endif
#ifdef _SHELLAPI_H
#ifndef SHARD_PATH
#define SHARD_PATH 2
#endif
#ifndef SHARD_PIDL
#define SHARD_PIDL 1
#endif
#ifndef SHORTCUT_OVERWRITE
#define SHORTCUT_OVERWRITE 1
#endif
#endif
#ifdef VELO_STDLIB_H
#ifndef EXIT_FAILURE
#define EXIT_FAILURE 1
#endif
#ifndef EXIT_SUCCESS
#define EXIT_SUCCESS 0
#endif
#ifndef RAND_MAX
#define RAND_MAX 0x7FFF
#endif
#endif
#ifdef _TLHELP32_H
#ifndef LF32_BIGBLOCK
#define LF32_BIGBLOCK 16
#endif
#ifndef LF32_DECOMMIT
#define LF32_DECOMMIT 8
#endif
#endif
#ifdef _WINBASE_H
#ifndef CLRIR
#define CLRIR 11
#endif
#ifndef COMMPROP_INITIALIZED
#define COMMPROP_INITIALIZED 0xE73CF52EU
#endif
#ifndef EV_POWER
#define EV_POWER 0x2000
#endif
#ifndef IE_BADID
#define IE_BADID (-1)
#endif
#ifndef IE_BAUDRATE
#define IE_BAUDRATE (-12)
#endif
#ifndef IE_BYTESIZE
#define IE_BYTESIZE (-11)
#endif
#ifndef IE_DEFAULT
#define IE_DEFAULT (-5)
#endif
#ifndef IE_HARDWARE
#define IE_HARDWARE (-10)
#endif
#ifndef IE_MEMORY
#define IE_MEMORY (-4)
#endif
#ifndef IE_NOPEN
#define IE_NOPEN (-3)
#endif
#ifndef IE_OPEN
#define IE_OPEN (-2)
#endif
#ifndef LMEM_VALID_FLAGS
#define LMEM_VALID_FLAGS 0xF72
#endif
#ifndef LPTx
#define LPTx 128
#endif
#ifndef MEM_AUTO_COMMIT
#define MEM_AUTO_COMMIT 0x200000
#endif
#ifndef OPEN_FOR_LOADER
#define OPEN_FOR_LOADER 6
#endif
#ifndef SETIR
#define SETIR 10
#endif
#ifndef VER_PLATFORM_WIN32_HH
#define VER_PLATFORM_WIN32_HH 3
#endif
#endif
#ifdef _WINERROR_H
#ifndef NTE_OP_OK
#define NTE_OP_OK 0
#endif
#ifndef PERSIST_E_NOTSELFSIZING
#define PERSIST_E_NOTSELFSIZING (-2146762741)
#endif
#ifndef PERSIST_E_SIZEDEFINITE
#define PERSIST_E_SIZEDEFINITE (-2146762743)
#endif
#ifndef PERSIST_E_SIZEINDEFINITE
#define PERSIST_E_SIZEINDEFINITE (-2146762742)
#endif
#endif
#ifdef _WINGDI_H
#ifndef BS_MONOPATTERN
#define BS_MONOPATTERN 9
#endif
#ifndef CP_NONE
#define CP_NONE 0
#endif
#ifndef CP_RECTANGLE
#define CP_RECTANGLE 1
#endif
#ifndef CP_REGION
#define CP_REGION 2
#endif
#ifndef MAX_OBJ_TYPE
#define MAX_OBJ_TYPE 13
#endif
#ifndef MIN_OBJ_TYPE
#define MIN_OBJ_TYPE 1
#endif
#ifndef R2_LAST
#define R2_LAST 16
#endif
#ifndef RGN_ERROR
#define RGN_ERROR 0
#endif
#ifndef RGN_MAX
#define RGN_MAX 5
#endif
#ifndef RGN_MIN
#define RGN_MIN 1
#endif
#endif
#ifdef _WINNLS_H
#ifndef CAL_HIRJI
#define CAL_HIRJI 6
#endif
#ifndef LOCALE_SYEARMONTH
#define LOCALE_SYEARMONTH 0x1020
#endif
#ifndef WC_DEFAULTCHECK
#define WC_DEFAULTCHECK 0x100
#endif
#endif
#ifdef _WINNT_H
#ifndef EXCEPTION_COLLIDED_UNWIND
#define EXCEPTION_COLLIDED_UNWIND 64
#endif
#ifndef EXCEPTION_EXIT_UNWIND
#define EXCEPTION_EXIT_UNWIND 4
#endif
#ifndef EXCEPTION_NESTED_CALL
#define EXCEPTION_NESTED_CALL 16
#endif
#ifndef EXCEPTION_STACK_INVALID
#define EXCEPTION_STACK_INVALID 8
#endif
#ifndef EXCEPTION_TARGET_UNWIND
#define EXCEPTION_TARGET_UNWIND 32
#endif
#ifndef EXCEPTION_UNWIND
#define EXCEPTION_UNWIND 102
#endif
#ifndef EXCEPTION_UNWINDING
#define EXCEPTION_UNWINDING 2
#endif
#ifndef FILE_ATTRIBUTE_ATOMIC_WRITE
#define FILE_ATTRIBUTE_ATOMIC_WRITE 0x200
#endif
#ifndef FILE_ATTRIBUTE_ROMSTATICREF
#define FILE_ATTRIBUTE_ROMSTATICREF 0x1000
#endif
#ifndef FILE_ATTRIBUTE_XACTION_WRITE
#define FILE_ATTRIBUTE_XACTION_WRITE 0x400
#endif
#ifndef IMAGE_SUBSYSTEM_WINDOWS_OLD_CE_GUI
#define IMAGE_SUBSYSTEM_WINDOWS_OLD_CE_GUI 4
#endif
#ifndef PROCESSOR_ARCHITECTURE_SHx
#define PROCESSOR_ARCHITECTURE_SHx 4
#endif
#ifndef PROCESSOR_ARM720
#define PROCESSOR_ARM720 0x720
#endif
#ifndef PROCESSOR_ARM820
#define PROCESSOR_ARM820 0x820
#endif
#ifndef PROCESSOR_ARM920
#define PROCESSOR_ARM920 0x920
#endif
#ifndef PROCESSOR_HITACHI_SH3
#define PROCESSOR_HITACHI_SH3 0x2713
#endif
#ifndef PROCESSOR_INTEL_860
#define PROCESSOR_INTEL_860 0x35C
#endif
#ifndef PROCESSOR_MIPS_R2000
#define PROCESSOR_MIPS_R2000 0x7D0
#endif
#ifndef PROCESSOR_MIPS_R3000
#define PROCESSOR_MIPS_R3000 0xBB8
#endif
#ifndef PROCESSOR_PPC_601
#define PROCESSOR_PPC_601 0x259
#endif
#ifndef PROCESSOR_PPC_603
#define PROCESSOR_PPC_603 0x25B
#endif
#ifndef PROCESSOR_PPC_604
#define PROCESSOR_PPC_604 0x25C
#endif
#ifndef PROCESSOR_PPC_620
#define PROCESSOR_PPC_620 0x26C
#endif
#ifndef PROCESSOR_PPC_821
#define PROCESSOR_PPC_821 0x335
#endif
#ifndef PROCESSOR_SHx_SH3
#define PROCESSOR_SHx_SH3 103
#endif
#ifndef PROCESSOR_SHx_SH4
#define PROCESSOR_SHx_SH4 104
#endif
#ifndef PROCESSOR_STRONGARM
#define PROCESSOR_STRONGARM 0xA11
#endif
#ifndef REG_LEGAL_CHANGE_FILTER
#define REG_LEGAL_CHANGE_FILTER 15
#endif
#ifndef STATUS_INSTRUCTION_MISALIGNMENT
#define STATUS_INSTRUCTION_MISALIGNMENT 0xC00000AAU
#endif
#ifndef STATUS_INVALID_PARAMETER
#define STATUS_INVALID_PARAMETER 0xC000000DU
#endif
#ifndef STATUS_INVALID_SYSTEM_SERVICE
#define STATUS_INVALID_SYSTEM_SERVICE 0xC000001CU
#endif
#ifndef STATUS_SUCCESS
#define STATUS_SUCCESS 0
#endif
#ifndef STATUS_UNSUCCESSFUL
#define STATUS_UNSUCCESSFUL 0xC0000001U
#endif
#ifndef STATUS_USER_BREAK
#define STATUS_USER_BREAK 0x80000113U
#endif
#endif
#ifdef _WINREG_H
#ifndef WIN31_CLASS
#define WIN31_CLASS 0
#endif
#endif
#ifdef _WINSOCK_H
#ifndef AF_PAGER
#define AF_PAGER 21
#endif
#ifndef AF_RBDS
#define AF_RBDS 23
#endif
#ifndef EADDRINUSE
#define EADDRINUSE 0x2740
#endif
#ifndef EADDRNOTAVAIL
#define EADDRNOTAVAIL 0x2741
#endif
#ifndef EAFNOSUPPORT
#define EAFNOSUPPORT 0x273F
#endif
#ifndef EALREADY
#define EALREADY 0x2735
#endif
#ifndef ECONNABORTED
#define ECONNABORTED 0x2745
#endif
#ifndef ECONNREFUSED
#define ECONNREFUSED 0x274D
#endif
#ifndef ECONNRESET
#define ECONNRESET 0x2746
#endif
#ifndef EDESTADDRREQ
#define EDESTADDRREQ 0x2737
#endif
#ifndef EDQUOT
#define EDQUOT 0x2755
#endif
#ifndef EHOSTDOWN
#define EHOSTDOWN 0x2750
#endif
#ifndef EHOSTUNREACH
#define EHOSTUNREACH 0x2751
#endif
#ifndef EINPROGRESS
#define EINPROGRESS 0x2734
#endif
#ifndef EISCONN
#define EISCONN 0x2748
#endif
#ifndef ELOOP
#define ELOOP 0x274E
#endif
#ifndef EMSGSIZE
#define EMSGSIZE 0x2738
#endif
#ifndef ENAMETOOLONG
#define ENAMETOOLONG 0x274F
#endif
#ifndef ENETDOWN
#define ENETDOWN 0x2742
#endif
#ifndef ENETRESET
#define ENETRESET 0x2744
#endif
#ifndef ENETUNREACH
#define ENETUNREACH 0x2743
#endif
#ifndef ENOBUFS
#define ENOBUFS 0x2747
#endif
#ifndef ENOPROTOOPT
#define ENOPROTOOPT 0x273A
#endif
#ifndef ENOTCONN
#define ENOTCONN 0x2749
#endif
#ifndef ENOTEMPTY
#define ENOTEMPTY 0x2752
#endif
#ifndef ENOTSOCK
#define ENOTSOCK 0x2736
#endif
#ifndef EOPNOTSUPP
#define EOPNOTSUPP 0x273D
#endif
#ifndef EPFNOSUPPORT
#define EPFNOSUPPORT 0x273E
#endif
#ifndef EPROCLIM
#define EPROCLIM 0x2753
#endif
#ifndef EPROTONOSUPPORT
#define EPROTONOSUPPORT 0x273B
#endif
#ifndef EPROTOTYPE
#define EPROTOTYPE 0x2739
#endif
#ifndef EREMOTE
#define EREMOTE 0x2757
#endif
#ifndef ESHUTDOWN
#define ESHUTDOWN 0x274A
#endif
#ifndef ESOCKTNOSUPPORT
#define ESOCKTNOSUPPORT 0x273C
#endif
#ifndef ESTALE
#define ESTALE 0x2756
#endif
#ifndef ETIMEDOUT
#define ETIMEDOUT 0x274C
#endif
#ifndef ETOOMANYREFS
#define ETOOMANYREFS 0x274B
#endif
#ifndef EUSERS
#define EUSERS 0x2754
#endif
#ifndef EWOULDBLOCK
#define EWOULDBLOCK 0x2733
#endif
#ifndef SO_SECURE
#define SO_SECURE 0x2001
#endif
#ifndef SO_SEC_NONE
#define SO_SEC_NONE 0x2002
#endif
#ifndef SO_SEC_SSL
#define SO_SEC_SSL 0x2004
#endif
#endif
#ifdef _WINUSER_H
#ifndef CBS_EX_CONSTSTRINGDATA
#define CBS_EX_CONSTSTRINGDATA 2
#endif
#ifndef CB_MSGMAX
#define CB_MSGMAX 0x163
#endif
#ifndef CB_MULTIPLEADDSTRING
#define CB_MULTIPLEADDSTRING 0x163
#endif
#ifndef COLOR_LASTITEM
#define COLOR_LASTITEM 0x4000001B
#endif
#ifndef COLOR_STATICTEXT
#define COLOR_STATICTEXT 0x4000001A
#endif
#ifndef CTLCOLOR_SCOLLBAR
#define CTLCOLOR_SCOLLBAR 5
#endif
#ifndef DFCS_CAPTIONOKBTN
#define DFCS_CAPTIONOKBTN 128
#endif
#ifndef ES_COMBOBOX
#define ES_COMBOBOX 0x200
#endif
#ifndef EW_EXITANDEXECAPP
#define EW_EXITANDEXECAPP 68
#endif
#ifndef EW_REBOOTSYSTEM
#define EW_REBOOTSYSTEM 67
#endif
#ifndef EW_RESTARTWINDOWS
#define EW_RESTARTWINDOWS 66
#endif
#ifndef GW_MAX
#define GW_MAX 5
#endif
#ifndef HSHELL_CAPSLOCK
#define HSHELL_CAPSLOCK 8
#endif
#ifndef INI_INTL
#define INI_INTL 1
#endif
#ifndef INPUT_HARDWARE
#define INPUT_HARDWARE 2
#endif
#ifndef INPUT_KEYBOARD
#define INPUT_KEYBOARD 1
#endif
#ifndef INPUT_MOUSE
#define INPUT_MOUSE 0
#endif
#ifndef LBS_EX_CONSTSTRINGDATA
#define LBS_EX_CONSTSTRINGDATA 2
#endif
#ifndef LB_MSGMAX
#define LB_MSGMAX 0x1B1
#endif
#ifndef LB_MULTIPLEADDSTRING
#define LB_MULTIPLEADDSTRING 0x1B1
#endif
#ifndef MSGSRC_HARDWARE_KEYBOARD
#define MSGSRC_HARDWARE_KEYBOARD 2
#endif
#ifndef MSGSRC_SOFTWARE_POST
#define MSGSRC_SOFTWARE_POST 1
#endif
#ifndef MSGSRC_UNKNOWN
#define MSGSRC_UNKNOWN 0
#endif
#ifndef SPI_GETBATTERYIDLETIMEOUT
#define SPI_GETBATTERYIDLETIMEOUT 252
#endif
#ifndef SPI_GETEXTERNALIDLETIMEOUT
#define SPI_GETEXTERNALIDLETIMEOUT 254
#endif
#ifndef SPI_GETWAKEUPIDLETIMEOUT
#define SPI_GETWAKEUPIDLETIMEOUT 0x100
#endif
#ifndef SPI_SETBATTERYIDLETIMEOUT
#define SPI_SETBATTERYIDLETIMEOUT 251
#endif
#ifndef SPI_SETEXTERNALIDLETIMEOUT
#define SPI_SETEXTERNALIDLETIMEOUT 253
#endif
#ifndef SPI_SETWAKEUPIDLETIMEOUT
#define SPI_SETWAKEUPIDLETIMEOUT 255
#endif
#ifndef VK_APOSTROPHE
#define VK_APOSTROPHE 222
#endif
#ifndef VK_BACKQUOTE
#define VK_BACKQUOTE 192
#endif
#ifndef VK_BACKSLASH
#define VK_BACKSLASH 220
#endif
#ifndef VK_COMMA
#define VK_COMMA 188
#endif
#ifndef VK_EQUAL
#define VK_EQUAL 187
#endif
#ifndef VK_HYPHEN
#define VK_HYPHEN 189
#endif
#ifndef VK_LBRACKET
#define VK_LBRACKET 219
#endif
#ifndef VK_OEM_102
#define VK_OEM_102 226
#endif
#ifndef VK_PERIOD
#define VK_PERIOD 190
#endif
#ifndef VK_RBRACKET
#define VK_RBRACKET 221
#endif
#ifndef VK_SEMICOLON
#define VK_SEMICOLON 186
#endif
#ifndef VK_SLASH
#define VK_SLASH 191
#endif
#ifndef WM_NETCONNECT
#define WM_NETCONNECT 0x3FE
#endif
#ifndef WS_EX_ABOVESTARTUP
#define WS_EX_ABOVESTARTUP 0x20000000
#endif
#ifndef WS_EX_INK
#define WS_EX_INK 0x10000000
#endif
#ifndef WS_EX_NOANIMATION
#define WS_EX_NOANIMATION 0x4000000
#endif
#ifndef WS_EX_NODRAG
#define WS_EX_NODRAG 0x40000000
#endif
#endif
#endif

#if VELO_WCE == 101
#ifdef _COMMCTRL_H
#ifndef LVS_EX_IMAGEHEADER
#define LVS_EX_IMAGEHEADER 128
#endif
#endif
#ifdef _WINNLS_H
#ifndef CAL_HIRJI
#define CAL_HIRJI 6
#endif
#ifndef LOCALE_SYEARMONTH
#define LOCALE_SYEARMONTH 0x1020
#endif
#ifndef WC_DEFAULTCHECK
#define WC_DEFAULTCHECK 0x100
#endif
#endif
#ifdef _WINUSER_H
#ifndef WS_EX_INK
#define WS_EX_INK 0x10000000
#endif
#endif
#endif
