include_guard(GLOBAL)

get_filename_component(VELO_TOOLCHAIN_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
find_package(Python3 REQUIRED COMPONENTS Interpreter)
enable_language(ASM)

set(VELO_EXPORTS_DIR "${VELO_TOOLCHAIN_ROOT}/exports/ce${VELO_CE_VERSION}")
if(NOT IS_DIRECTORY "${VELO_EXPORTS_DIR}")
    message(FATAL_ERROR "No export lists for VELO_CE_VERSION=${VELO_CE_VERSION}")
endif()

add_library(velo_headers INTERFACE)
target_include_directories(velo_headers SYSTEM INTERFACE "${VELO_TOOLCHAIN_ROOT}/include")
add_library(velo::headers ALIAS velo_headers)

file(GLOB VELO_RUNTIME_SOURCES "${VELO_TOOLCHAIN_ROOT}/runtime/*.c" "${VELO_TOOLCHAIN_ROOT}/runtime/compiler-rt/*.c")
add_library(velo_runtime STATIC EXCLUDE_FROM_ALL ${VELO_RUNTIME_SOURCES})
target_compile_options(velo_runtime PRIVATE -fno-builtin -w)
add_library(velo::runtime ALIAS velo_runtime)

file(GLOB VELO_EXPORT_LISTS "${VELO_EXPORTS_DIR}/*.txt")
file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/velo/ce${VELO_CE_VERSION}")
foreach(exports IN LISTS VELO_EXPORT_LISTS)
    get_filename_component(dll "${exports}" NAME_WE)
    string(TOUPPER "${dll}" dll_upper)
    set(stubs "${CMAKE_BINARY_DIR}/velo/ce${VELO_CE_VERSION}/${dll}.S")
    add_custom_command(
        OUTPUT "${stubs}"
        COMMAND "${Python3_EXECUTABLE}" "${VELO_TOOLCHAIN_ROOT}/tools/mkimplib.py" "${exports}" "${dll_upper}.dll" "${stubs}"
        DEPENDS "${exports}" "${VELO_TOOLCHAIN_ROOT}/tools/mkimplib.py"
        VERBATIM)
    add_library(velo_${dll} STATIC EXCLUDE_FROM_ALL "${stubs}")
    add_library(velo::${dll} ALIAS velo_${dll})
endforeach()

function(_velo_link target script)
    set_target_properties(${target} PROPERTIES SUFFIX ".elf" LINK_DEPENDS "${script}")
    target_link_options(${target} PRIVATE -T "${script}")
    target_link_libraries(${target} PRIVATE velo::headers velo::runtime velo::coredll)
endfunction()

function(_velo_pe target output)
    set_property(TARGET ${target} APPEND PROPERTY LINK_DEPENDS "${VELO_TOOLCHAIN_ROOT}/tools/mkpe.py")
    add_custom_command(TARGET ${target} POST_BUILD
        COMMAND "${Python3_EXECUTABLE}" "${VELO_TOOLCHAIN_ROOT}/tools/mkpe.py" "$<TARGET_FILE:${target}>" "$<TARGET_FILE_DIR:${target}>/${output}" ${ARGN}
        VERBATIM)
endfunction()

function(_velo_resources target out_options)
    set(options "")
    set(dependencies "")
    set(scripts "")
    foreach(resource IN LISTS ARGN)
        get_filename_component(resource "${resource}" ABSOLUTE)
        if(resource MATCHES "\\.rc$")
            list(APPEND scripts "${resource}")
        else()
            list(APPEND dependencies "${resource}")
        endif()
    endforeach()
    if(scripts)
        find_program(VELO_RC llvm-rc HINTS "${VELO_LLVM_ROOT}/bin" REQUIRED)
    endif()
    foreach(script IN LISTS scripts)
        get_filename_component(name "${script}" NAME_WE)
        get_filename_component(directory "${script}" DIRECTORY)
        set(compiled "${CMAKE_CURRENT_BINARY_DIR}/${target}_${name}.res")
        add_custom_command(
            OUTPUT "${compiled}"
            COMMAND "${VELO_RC}" -D "_WIN32_WCE=${VELO_CE_VERSION}00" -I "${VELO_TOOLCHAIN_ROOT}/include" -I "${directory}" -FO "${compiled}" -- "${script}"
            DEPENDS "${script}" ${dependencies}
            VERBATIM)
        target_sources(${target} PRIVATE "${compiled}")
        set_property(TARGET ${target} APPEND PROPERTY LINK_DEPENDS "${compiled}")
        list(APPEND options "--resources=${compiled}")
    endforeach()
    set(${out_options} ${options} PARENT_SCOPE)
endfunction()

function(_velo_require_exports target)
    foreach(export IN LISTS ARGN)
        string(REGEX REPLACE "^[^=]*=" "" symbol "${export}")
        target_link_options(${target} PRIVATE "--undefined=${symbol}")
    endforeach()
endfunction()

function(velo_add_executable target)
    cmake_parse_arguments(PARSE_ARGV 1 VELO "EXCLUDE_FROM_ALL" "OUTPUT;ICON" "RESOURCES")
    if(NOT VELO_OUTPUT)
        set(VELO_OUTPUT "${target}.exe")
    endif()
    set(exclude "")
    if(VELO_EXCLUDE_FROM_ALL)
        set(exclude EXCLUDE_FROM_ALL)
    endif()
    add_executable(${target} ${exclude} ${VELO_UNPARSED_ARGUMENTS})
    _velo_link(${target} "${VELO_TOOLCHAIN_ROOT}/ld/exe.ld")
    set(options "")
    if(VELO_ICON)
        get_filename_component(icon "${VELO_ICON}" ABSOLUTE)
        set(options "--icon=${icon}")
    endif()
    _velo_resources(${target} resource_options ${VELO_RESOURCES})
    _velo_pe(${target} "${VELO_OUTPUT}" ${options} ${resource_options})
endfunction()

function(velo_add_library target)
    cmake_parse_arguments(PARSE_ARGV 1 VELO "EXCLUDE_FROM_ALL" "OUTPUT;EXPORTS_FILE" "EXPORTS;RESOURCES")
    if(NOT VELO_OUTPUT)
        set(VELO_OUTPUT "${target}.dll")
    endif()
    if(NOT VELO_EXPORTS AND NOT VELO_EXPORTS_FILE)
        message(FATAL_ERROR "velo_add_library(${target}) needs EXPORTS or EXPORTS_FILE")
    endif()
    set(exclude "")
    if(VELO_EXCLUDE_FROM_ALL)
        set(exclude EXCLUDE_FROM_ALL)
    endif()
    add_executable(${target} ${exclude} ${VELO_UNPARSED_ARGUMENTS})
    _velo_link(${target} "${VELO_TOOLCHAIN_ROOT}/ld/dll.ld")
    set(options "")
    _velo_require_exports(${target} ${VELO_EXPORTS})
    if(VELO_EXPORTS)
        string(JOIN "," exports ${VELO_EXPORTS})
        list(APPEND options "--exports=${exports}")
    endif()
    if(VELO_EXPORTS_FILE)
        get_filename_component(exports_file "${VELO_EXPORTS_FILE}" ABSOLUTE)
        file(STRINGS "${exports_file}" file_exports)
        _velo_require_exports(${target} ${file_exports})
        list(APPEND options "--exports-file=${exports_file}")
        set_property(TARGET ${target} APPEND PROPERTY LINK_DEPENDS "${exports_file}")
    endif()
    _velo_resources(${target} resource_options ${VELO_RESOURCES})
    _velo_pe(${target} "${VELO_OUTPUT}" ${options} ${resource_options})
endfunction()
