set(CMAKE_SYSTEM_NAME Generic)

get_filename_component(VELO_TOOLCHAIN_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)

set(VELO_CE_VERSION 1 CACHE STRING "Windows CE version to target: 1 or 2")
set_property(CACHE VELO_CE_VERSION PROPERTY STRINGS 1 2)
set(VELO_ARCH mips CACHE STRING "Processor to target: mips or sh3")
set_property(CACHE VELO_ARCH PROPERTY STRINGS mips sh3)

if(VELO_ARCH STREQUAL "mips")
    set(CMAKE_SYSTEM_PROCESSOR mips)
    set(VELO_TARGET mipsel-unknown-none-elf)
    set(VELO_TARGET_FLAGS "-march=mips1 -msoft-float -mno-abicalls -fno-pic -G0 -mno-check-zero-division")
    set(VELO_ARCH_DEFINES "")
    set(VELO_LLVM_DESCRIPTION "LLVM install with the MIPS backend")
elseif(VELO_ARCH STREQUAL "sh3")
    set(CMAKE_SYSTEM_PROCESSOR sh3)
    set(VELO_TARGET sh3el-unknown-none-elf)
    set(VELO_TARGET_FLAGS "-fno-pic")
    set(VELO_ARCH_DEFINES SHx SH3 _SH3_)
    set(VELO_LLVM_DESCRIPTION "LLVM install with the SuperH backend")
else()
    message(FATAL_ERROR "VELO_ARCH must be mips or sh3, not ${VELO_ARCH}")
endif()

if(NOT VELO_LLVM_ROOT)
    execute_process(COMMAND brew --prefix llvm OUTPUT_VARIABLE VELO_BREW_LLVM OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(VELO_BREW_LLVM)
        set(VELO_LLVM_DEFAULT "${VELO_BREW_LLVM}")
    else()
        find_program(VELO_CLANG clang HINTS /opt/homebrew/opt/llvm/bin REQUIRED)
        get_filename_component(VELO_CLANG_BIN "${VELO_CLANG}" DIRECTORY)
        get_filename_component(VELO_LLVM_DEFAULT "${VELO_CLANG_BIN}" DIRECTORY)
    endif()
    set(VELO_LLVM_ROOT "${VELO_LLVM_DEFAULT}" CACHE PATH "${VELO_LLVM_DESCRIPTION}")
endif()

find_program(VELO_LLD ld.lld HINTS "${VELO_LLVM_ROOT}/bin" /opt/homebrew/opt/lld/bin REQUIRED)

set(CMAKE_C_COMPILER "${VELO_LLVM_ROOT}/bin/clang")
set(CMAKE_CXX_COMPILER "${VELO_LLVM_ROOT}/bin/clang++")
set(CMAKE_ASM_COMPILER "${VELO_LLVM_ROOT}/bin/clang")
set(CMAKE_AR "${VELO_LLVM_ROOT}/bin/llvm-ar")
set(CMAKE_RANLIB "${VELO_LLVM_ROOT}/bin/llvm-ranlib")
set(CMAKE_LINKER "${VELO_LLD}")
set(CMAKE_C_COMPILER_TARGET ${VELO_TARGET})
set(CMAKE_CXX_COMPILER_TARGET ${VELO_TARGET})
set(CMAKE_ASM_COMPILER_TARGET ${VELO_TARGET})
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES VELO_ARCH VELO_LLVM_ROOT)

set(CMAKE_C_FLAGS_INIT "${VELO_TARGET_FLAGS} -fshort-wchar -ffreestanding -ffunction-sections -fdata-sections -D_WIN32_WCE=${VELO_CE_VERSION}00")
foreach(define IN LISTS VELO_ARCH_DEFINES)
    string(APPEND CMAKE_C_FLAGS_INIT " -D${define}")
endforeach()
set(CMAKE_CXX_FLAGS_INIT "${CMAKE_C_FLAGS_INIT} -std=c++20 -fno-exceptions -fno-rtti -fno-threadsafe-statics")
set(CMAKE_ASM_FLAGS_INIT "${VELO_TARGET_FLAGS}")
set(CMAKE_BUILD_TYPE_INIT MinSizeRel)
set(CMAKE_C_FLAGS_RELEASE_INIT "-Os")
set(CMAKE_C_FLAGS_MINSIZEREL_INIT "-Os")
set(CMAKE_CXX_FLAGS_RELEASE_INIT "-Os")
set(CMAKE_CXX_FLAGS_MINSIZEREL_INIT "-Os")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-static --emit-relocs --gc-sections")
set(CMAKE_C_LINK_EXECUTABLE "<CMAKE_LINKER> <LINK_FLAGS> <CMAKE_C_LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
set(CMAKE_CXX_LINK_EXECUTABLE "<CMAKE_LINKER> <LINK_FLAGS> <CMAKE_CXX_LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")

if(NOT DEFINED CMAKE_C_COMPILER_LAUNCHER)
    set(CMAKE_C_COMPILER_LAUNCHER "${VELO_TOOLCHAIN_ROOT}/tools/velo-cc")
    set(CMAKE_ASM_COMPILER_LAUNCHER "${VELO_TOOLCHAIN_ROOT}/tools/velo-cc")
endif()
if(NOT DEFINED CMAKE_CXX_COMPILER_LAUNCHER)
    set(CMAKE_CXX_COMPILER_LAUNCHER "${VELO_TOOLCHAIN_ROOT}/tools/velo-cc")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

list(APPEND CMAKE_MODULE_PATH "${VELO_TOOLCHAIN_ROOT}/cmake")
